### ISSUE TITLE
Dev Server Error

### ISSUE THREAD

**Issue by paulmathis** [deskpro/apps-boilerplate#3]
When running `npm run dev` I receive the following error. Occurs on both OSX and Ubuntu

    paul@ubuntu:~/apps-boilerplate$ npm run dev

    > @deskpro/apps-boilerplate@0.2.1 dev /home/paul/apps-boilerplate
    > dpat server .

    module.js:559
        throw err;
        ^

    Error: Cannot find module '../lib/util/addDevServerEntrypoints'
        at Function.Module._resolveFilename (module.js:557:15)
        at Function.Module._load (module.js:484:25)
        at Module.require (module.js:606:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/home/paul/apps-boilerplate/node_modules/@deskpro/apps-
    dpat/node_modules/.bin/webpack-dev-server:9:33)
        at Module._compile (module.js:662:30)
        at Object.Module._extensions..js (module.js:673:10)
        at Module.load (module.js:575:32)
        at tryModuleLoad (module.js:515:12)
        at Function.Module._load (module.js:507:3)
    dpat server exited with code 1

**Comment by helstern** [comment]
Hi @paulmathis, we've recently made some changes that might solve your problem. Could you give another try? Also it would be useful to know your version of npm and node.

**Comment by paulmathis** [comment]
Hey @helstern, I made a fresh clone of the boilerplate, and it is throwing the same error. I'm running Node v8.10.0 and npm 5.6.0.

**Comment by helstern** [comment]
Hi @paulmathis, we've identified the problem: it looks like webpack and webpack-dev-server entrypoints are not correctly symlinked into 'node-modules/.bin'. I've added a postinstall script to correct this as a workaround, while we work out a proper fix

I've tested using the official docker images for node 8 (node v8.10.0 and npm 5.6.0) so you should be able to get it working by just cloning the master branch. if you use the docker images and run as root, make sure you run `npm install --unsafe-perm`, otherwise the npm will complain about the postinstall script.

**Comment by helstern** [comment]
@paulmathis, this issue has been fixed now and there is no need to use that workaround. thanks for reporting it to us!
